---
- hosts: all
  pre_tasks:
    # The version string below is the highest of all those in roles' metadata:
    # "min_ansible_version". It needs to be kept manually up-to-date.
    - name: Verify Ansible meets min required version
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this version of Pulp 3 Installer."
  tasks:
    - name: Dynamically include prereq roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp.pulp_installer.pulp_database
        - pulp.pulp_installer.pulp_redis
        - pulp.pulp_installer.pulp_database_config
        - pulp.pulp_installer.pulp_api
        - pulp.pulp_installer.pulp_content
        - pulp.pulp_installer.pulp_resource_manager
        - pulp.pulp_installer.pulp_workers
        - pulp.pulp_installer.pulp_health_check
        - pulp.pulp_installer.pulp_webserver
        - pulp.pulp_installer.pulp_devel
      loop_control:
        loop_var: roleinputvar
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
