# Molecule runs tests in containers.
sudo: required
services:
- docker

# Manually defining a build matrix is more cumbersome than using a tool like
# tox-travis. However, this avoids adding yet another layer of abstraction, and
# it offers great flexibility. See:
# https://stackoverflow.com/questions/37016688/how-to-run-tox-with-travis-ci
language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
install:
- pip install --upgrade pip
- pip install tox
script:
- tox
