---
- hosts: all
  vars:
    # https://docs.pulpproject.org/en/3.0/nightly/installation/configuration.html#secret-key
    pulp_postgresql_host: "{{ ansible_nodename }}"
    pulp_secret_key: "unsafe_default"
    pulp_default_admin_password: password
    pulp_install_plugins:
      # pulp-python:
      #   app_label: "pulp_python"
      #   source_dir: "/home/vagrant/devel/pulp_python"
      pulp-file:
        app_label: "pulp_file"
        # source_dir: "/home/vagrant/devel/pulp_file"
  roles:
    - pulp3-postgresql
    - pulp3-workers
    - pulp3-resource-manager
    - pulp3-webserver
