---
- hosts: all
  pre_tasks:
    # The version string below is the highest of all those in roles' metadata:
    # "min_ansible_version". It needs to be kept manually up-to-date.
    - name: Verify Ansible meets min required version
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: >
          "You must update Ansible to at least 2.9 to use this version of Pulp 3 Installer."
  roles:
    - pulp.pulp_installer.pulp_all_services
    - pulp.pulp_installer.pulp_devel
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
