---
# installation of nginx on ubuntu doesn't do this automatically
- name: Create nginx user
  user:
    name: nginx
    system: true
  when: ansible_distribution == 'Ubuntu'
  become: yes

- name: Find site-packages directory
  find:
    paths: '{{ pulp_install_dir }}'
    recurse: true
    file_type: directory
    patterns: site-packages
  register: result

- name: Assert one directory has been found
  assert:
    that: '{{ result.matched }} == 1'

- name: Set fact referencing Pulp's static files directory
  set_fact:
    pulp_webserver_static_dir: '{{ result.files[0].path }}/rest_framework'

- block:

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Install Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: reload nginx

    - name: Create snippets symbolic link
      file:
        src: '{{ result.files[0].path }}/{{item.key}}/app/webserver_snippets/nginx.conf'
        dest: '/etc/nginx/conf.d/{{ item.key }}'
        state: link
      with_dict: '{{ pulp_install_plugins }}'

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true

  become: true
