---
pulp_config_dir: "/etc/pulp"
pulp_settings_file: "{{ pulp_config_dir }}/settings.py"
pulp_group: pulp
pulp_workers:
  1:
    state: started
    enabled: true
  2:
    state: started
    enabled: true
  3:
    state: started
    enabled: true
  4:
    state: started
    enabled: true
