---
- block:

    - name: Install EPEL Release
      package:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install prerequisites
      package:
        name: '{{ pulp_preq_packages }}'
        state: present

    - name: Disable SELinux (Pulp 3 is currently incompatible with SELinux)
      selinux:
        policy: targeted
        state: permissive

    # Become root so as to search paths like /usr/sbin.
    - name: Find the nologin executable
      command: which nologin
      changed_when: False
      check_mode: False
      register: result

    - name: Create user {{ pulp_user }}
      user:
        name: '{{ pulp_user }}'
        shell: '{{ result.stdout.strip() }}'
        home: '{{ pulp_var_dir }}'
        system: true

    - name: Create temp dir for Pulp
      file:
        path: '{{ pulp_var_dir }}/tmp'
        state: directory
        owner: '{{ pulp_user }}'
        group: '{{ pulp_user }}'
        mode: 0775

    - name: Create cache dir for Pulp
      file:
        path: '{{ pulp_cache_dir }}'
        state: directory
        owner: '{{ pulp_user }}'
        group: '{{ pulp_user }}'
        mode: 0775

    - name: Create pulp install dir
      file:
        path: '{{ pulp_install_dir }}'
        state: directory
        owner: '{{ pulp_user }}'
        group: '{{ pulp_user }}'

  become: true

- block:

    - name: Install pulpcore packages from source
      pip:
        name: '{{ pulp_source_dir }}/{{ item }}'
        editable: yes
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_items:
        - pulpcore
        - plugin
      when: pulp_source_dir is defined

    - name: Include plugin specific pre tasks
      include_tasks: "{{ plugin.value.pre_task_file }}"
      with_dict: '{{ pulp_install_plugins }}'
      when: pulp_install_plugins[plugin.key].pre_task_file is defined
      loop_control:
        loop_var: plugin

    - name: Install Pulp plugins via PyPI
      pip:
        name: '{{ item.key }}'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_dict: '{{ pulp_install_plugins }}'
      when: pulp_install_plugins[item.key].source_dir is undefined

    - name: Install Pulp plugins from source
      pip:
        name: '{{ item.value.source_dir }}'
        editable: yes
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_dict: '{{ pulp_install_plugins }}'
      when: pulp_install_plugins[item.key].source_dir is defined

  become: true
  become_user: '{{ pulp_user }}'
