---
galaxy_info:
  author: Pulp
  description: Pulp content app
  company: Red Hat
  min_ansible_version: 2.4
  platforms:
    - name: Fedora
      versions:
        - 29
        - 30
  license: GPL-3.0
