# Standards: 0.1
# Depend on pulp3-redis for RQ.
galaxy_info:
  author: Pulp
  description: Pulp Resource Manager
  company: Red Hat
  min_ansible_version: 2.4
  platforms:
  - name: Fedora
    versions:
    - 28
  license: GPL-3.0
dependencies:
- role: pulp3-redis
