---
name: Pulp CI
on:
  push:
    branches:
      - '*'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Testing different python versions because of
      # https://pulp.plan.io/issues/5768#note-17
      matrix:
        include:
          - test_type: release-static
            ansible: "2.9"
            python: "2.7"
            toxpy: "27"
          - test_type: source-static
            ansible: "2.9"
            python: "3.6"
            toxpy: "36"
          - test_type: packages-static
            ansible: "2.10"
            python: "3.7"
            toxpy: "37"
          - test_type: release-dynamic
            ansible: "2.10"
            python: "3.8"
            toxpy: "38"
          - test_type: source-dynamic
            ansible: "2.9"
            python: "3.8"
            toxpy: "38"
          - test_type: packages-dynamic
            ansible: "2.9"
            python: "3.7"
            toxpy: "37"
          - test_type: release-upgrade
            ansible: "2.9"
            python: "2.7"
            toxpy: "27"
          - test_type: source-upgrade
            ansible: "2.10"
            python: "3.6"
            toxpy: "36"
          - test_type: packages-upgrade
            ansible: "2.10"
            python: "3.6"
            toxpy: "36"
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install testing tools
        run: |
          # Warning: Installing ansible via pip would break molecule in the tox environment
          sudo apt-get -yy install ansible
          pip install --upgrade pip
          # Dependency PyYAML is needed for compiling targets in the Makefile
          pip install tox PyYAML
      - name: Pulling images for PyPI upgrades
        if: matrix.test_type == 'release-upgrade' || matrix.test_type == 'source-upgrade'
        run: |
          docker pull quay.io/pulp/pulp-ci-dbuster:3.0.0
          docker pull quay.io/pulp/pulp_rpm-ci-f31:3.1.0
          docker pull quay.io/pulp/pulp_rpm-ci-c7:3.1.0
      - name: Pulling images for distro packages upgrades
        if: matrix.test_type == 'packages-upgrade'
        run: |
          docker pull quay.io/pulp/pulp-ci-pkgs-c7:3.3.1
          docker pull quay.io/pulp/pulp-ci-pkgs-c8:3.3.1
      - name: Run tox
        run: "make test TOX_ENV=py${{ matrix.toxpy }}-ansible${{ matrix.ansible }}-${{ matrix.test_type }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        shell: bash
